### ISSUE TITLE
Opening json file programmatically

### ISSUE THREAD

**Issue by dbuscombe-usgs** [2320sharon/NPZ_JSON_Converter#2]
I am attempting to read the json file, but ran into an error

```
import json
with open('npz_data.json') as f:
    json_data = json.load(f)
```

I get the error

`JSONDecodeError: Extra data: line 2 column 1 (char 899)`

I used [this](https://jsonlint.com/) to debug

and got the following message

`Error: Parse error on line 18:
...46668956043956045} {	"image_filename":
----------------------^
Expecting 'EOF', '}', ',', ']', got '{'`

which is at the end of the first row...

so, I made a new function to convert this data to csv. It is pasted below

```
with open('../json/npz_data.json') as f:
    json_txt = f.readlines()

npzdatadict = {}
fields = ['image_filename', 
'label_image_filename', 
'annotation_image_filename', 
'user_ID', 
'classes_array', 
'num_classes',
 'classes_integer', 
 'classes_present_integer', 
 'classes_present_array',
  'pen_width', 
  'CRF_theta', 
  'CRF_mu', 
  'CRF_downsample_factor', 
  'Classifier_downsample_factor', 
  'prob_of_unary_potential', 
  'doodle_spatial_density']

 # make fields
 for f in fields:
     npzdatadict[f]=[]

# update all fields
for entry in json_txt:
    wjdata = json.loads(entry)
    for f in fields:
        npzdatadict[f].append(wjdata[f])

import pandas as pd
#convert to pandas dataframe, then to csv
pd.DataFrame.from_dict(npzdatadict).to_csv('npz_meta.csv')
```

that works, but do you know why `json` doesn't load?

**Comment by 2320sharon** [comment]
This issue has been resolved by Pull Request #3 .
